name: Cloudflare Preview Deployment

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  deploy-to-cloudflare:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"

      - name: Wrangler Install
        run: npm install -g wrangler

      - name: Publish to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          PRODUCTION_BRANCH: "main"
          OUTPUT_DIRECTORY: "static"
        run: |
          IFS='/' read -ra fields <<< "$REPOSITORY"
          projectName="${fields[1]}"
          projectName=$(echo $projectName | sed 's/\./-/g')
          echo $projectName
          wrangler pages project list > project_list.txt
          if grep -q $projectName project_list.txt; then
            echo "Project found"
          else
            echo "Project not found"
            wrangler pages project create "$projectName" --production-branch "$PRODUCTION_BRANCH"
          fi
          wrangler pages publish "$OUTPUT_DIRECTORY" --project-name "$projectName"
